# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
auto_detect_solc = false
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
bytecode_hash = "none"
evm_version = "shanghai"
fuzz = { runs = 10_000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200
out = "out"
script = "script"
solc = "0.8.28"
src = "src"
test = "test"
remappings = [
  "@chainlink/contracts/=node_modules/@chainlink/contracts/src/v0.8/",
  "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "forge-std/=node_modules/forge-std/src/",
]
fs_permissions = [{ access = "read-write", path = "./" }]
via_ir = true

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
single_line_statement_blocks = "preserve"

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
optimism = "${OPTIMISM_RPC}"
arbitrum = "${ARBITRUM_RPC}"
base = "${BASE_RPC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_V2_KEY}", chain = 1 }
arbitrum = { key = "${ETHERSCAN_V2_KEY}", chain = 42161 }
optimism = { key = "${ETHERSCAN_V2_KEY}", chain = 10 }
base = { key = "${ETHERSCAN_V2_KEY}", chain = 8453 }
basesepolia = { key = "${ETHERSCAN_V2_KEY}", chain = 84532 }
