name: Build And Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: test
        run: |
          cp .env-example .env
          npm install
          npm test
          npm run coverage